version: '3.8'

services:
  backend:
    build:
      context: stugear_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
    command: php artisan queue:work --tries=3 # Add this line to run queue worker
  frontend:
    build:
      context: stugear_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  admin:
    build:
      context: stugear_admin
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      - backend