name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  config:
    name: Config project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Pull repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo -i
            cd root
            if [ -d "stugear" ]; then
              cd ./stugear
              git pull https://github.com/KhaiNguyenDuc/stugear.git --ff --no-edit
              wait
              cd ../
            else
              git clone https://github.com/KhaiNguyenDuc/stugear.git
              wait
            fi
          
  stop-old-container:
    name: Stop container
    runs-on: ubuntu-latest
    needs: config
    steps:
      - name: SSH into VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker ps -a --format '{{.ID}}' | xargs -r sudo docker stop
      
  remove-old-container:
    name: Remove container
    needs: stop-old-container
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker ps -a --format '{{.ID}}' | xargs -r sudo docker rm

  remove-old-images:
    name: Remove old image
    needs: remove-old-container
    runs-on: ubuntu-latest
    steps:
      - name: SSH into vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker images --quiet | xargs -r sudo docker rmi
          
 
  start-container:
    name: Deploy
    runs-on: ubuntu-latest
    needs: remove-old-images
    steps:
      - name: SSH into Vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd stugear
            sudo docker compose up --build -d
